server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          metadata:
            cors:
              allowedOrigins: http://localhost:3000
              allowedMethods: '*'
              allowedHeaders:
                - x-origin
                - Origin
                - Content-Type
                - Authorization

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**

eureka:
  client:
    register-with-eureka: true # Allow register with eureka
    fetch-registry: true # Allow get others from eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/ # where services will be registered and found
    instance:
      hostname: localhost # hostname

management:
  endpoints:
    web:
      exposure:
        include: '*'